### ISSUE TITLE
Browser refresh not working: "Cannot open Browser Refresh.sublime-package"

### ISSUE THREAD

**Issue by TrevorBurnham** [gcollazo/BrowserRefresh-Sublime#51]
I'm running Sublime Text 3 build 3059 on OS X 10.9.1, and installed Browser Refresh 0.3.0 via Package Control. At some point within the last week, my trusty Browser Refresh keyboard shortcut stopped refreshing my browser. If I have `auto_save` enabled, the current file will save, but the actual part where the browser refreshes does not occur, regardless of `browser_name`. Also, I get this error in the ST console:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
  File "BrowserRefresh in /Users/trevor/Library/Application Support/Sublime Text 3/Installed Packages/Browser Refresh.sublime-package", line 34, in run
zipimport.ZipImportError: bad local file header in /Users/trevor/Library/Application Support/Sublime Text 3/Installed Packages/Browser Refresh.sublime-package
```

I've tries reinstalling the package with Package Control. I've also tried manually installing it by cloning the repo, in which case the traceback changes slightly:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
  File "/Users/trevor/Library/Application Support/Sublime Text 3/Packages/Browser Refresh/BrowserRefresh.py", line 34, in run
    from mac import MacBrowserRefresh
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
OSError: zipimport: can not open file /Users/trevor/Library/Application Support/Sublime Text 3/Installed Packages/Browser Refresh.sublime-package
```

Checking out an older Browser Refresh commit does not help. Something else must have changed, but I can't think of anything in my setup that could have affected it. Any ideas?

**Comment by kayspiegel** [comment]
In addition the output in my sublime text 2 console on a mac:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 356, in run_
  File "./BrowserRefresh.py", line 26, in run
    print('Browser Refresh: "{}" {}'.format(_os, browsers))
ValueError: zero length field name in format
```

**Comment by robert-sy** [comment]
Have same problem as Kimberly using ST 2. Any solutions? I am total pc newb btw :P
