### ISSUE TITLE
Not working in ST3 under OS X 10.10.1

### ISSUE THREAD

**Issue by TrevorBurnham** [gcollazo/BrowserRefresh-Sublime#69]
I'm running Sublime Text stable build 3065 on a Mac with the latest stable OS. My trusty Browser Refresh keyboard shortcut stopped working recently, instead generating this error in the console:

    Traceback (most recent call last):
      File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 543, in run_
        return self.run(edit, **args)
      File "BrowserRefresh in /Users/trevor/Library/Application Support/Sublime Text 3/Installed Packages/Browser Refresh.sublime-package", line 34, in run
    zipimport.ZipImportError: bad local file header in /Users/trevor/Library/Application Support/Sublime Text 3/Installed Packages/Browser Refresh.sublime-package

I tried removing the Package Control-installed package and installing the latest `master` instead. That yielded a more specific error message:

    Traceback (most recent call last):
      File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 543, in run_
        return self.run(edit, **args)
      File "/Users/trevor/Library/Application Support/Sublime Text 3/Packages/Browser Refresh/BrowserRefresh.py", line 34, in run
        from mac import MacBrowserRefresh
      File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
    OSError: zipimport: can not open file /Users/trevor/Library/Application Support/Sublime Text 3/Installed Packages/Browser Refresh.sublime-package

Any idea why this error is occurring?

**Comment by TrevorBurnham** [comment]
Restarting Sublime Text seems to have resolved this issue for me.
