### ISSUE TITLE
Not working, got a traceback about ctypes

### ISSUE THREAD

**Issue by andymeneely** [gcollazo/BrowserRefresh-Sublime#70]
This doesn't seem to work for me. I get this stacktrace on the console:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
  File "BrowserRefresh in C:\Users\andy\AppData\Roaming\Sublime Text 3\Installed Packages\Browser Refresh.sublime-package", line 88, in run
  File "C:\Users\andy\AppData\Roaming\Sublime Text 3\Installed Packages\Browser Refresh.sublime-package\win\__init__.py", line 29, in safari
  File "C:\Users\andy\AppData\Roaming\Sublime Text 3\Installed Packages\Browser Refresh.sublime-package\win\pywinauto\application.py", line 927, in connect_
  File "C:\Users\andy\AppData\Roaming\Sublime Text 3\Installed Packages\Browser Refresh.sublime-package\win\pywinauto\application.py", line 1188, in process_from_module
ctypes.ArgumentError: argument 1: <class 'TypeError'>: expected LP_c_ulong instance instead of pointer to c_long_Array_2000
```

I was using BrowserRefresh v1.4.0

I'm in Windows 7, attempting with Firefox 35.0.1 (although it doesn't look like it got to the browser). Using SublimeText 3 build 3065.

**Comment by jessycormier** [comment]
I'm getting Simular Error

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
  File "BrowserRefresh in C:\Users\Jessy\AppData\Roaming\Sublime Text 3\Installed Packages\Browser Refresh.sublime-package", line 88, in run
  File "C:\Users\Jessy\AppData\Roaming\Sublime Text 3\Installed Packages\Browser Refresh.sublime-package\win\__init__.py", line 29, in safari
  File "C:\Users\Jessy\AppData\Roaming\Sublime Text 3\Installed Packages\Browser Refresh.sublime-package\win\pywinauto\application.py", line 927, in connect_
  File "C:\Users\Jessy\AppData\Roaming\Sublime Text 3\Installed Packages\Browser Refresh.sublime-package\win\pywinauto\application.py", line 1188, in process_from_module
ctypes.ArgumentError: argument 1: <class 'TypeError'>: expected LP_c_ulong instance instead of pointer to c_long_Array_2000
```

**Comment by r1f** [comment]
Same issue on Sublime Text 3 3083, Windows 7 x64, on Python 3.3.3 (v3.3.3:c3896275c0f6, Nov 18 2013, 21:19:30) [MSC v.1600 64 bit (AMD64)] 

Changing to a specific browser doesn't seem to fix it.
