### ISSUE TITLE
Browser Doesn't reload. (bad local file header in Browser Refresh.sublime-package)

### ISSUE THREAD

**Issue by ghost** [gcollazo/BrowserRefresh-Sublime#78]
When using the plugin, the file will save, but the browser won't actually reload.

Err from the console at every reload attempt:

> Traceback (most recent call last):
>  File "/opt/sublime_text/sublime_plugin.py", line 550, in run_
>    return self.run(edit, **args)
>  File "BrowserRefresh in /home/michael/.config/sublime-text-3/Installed Packages/Browser >Refresh.sublime-package", line 39, in run
> zipimport.ZipImportError: bad local file header in /home/username/.config/sublime-text-3/Installed >Packages/Browser Refresh.sublime-package

Running on Linux, ST3.

**Comment by aheissenberger** [comment]
stopped working for me too - same error in local console

**Comment by aheissenberger** [comment]
The problem starts when plugin gets installed (Package Manager or GIT):

```
reloading plugin Browser Refresh.BrowserRefresh
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
OSError: zipimport: can not open file /Users/ah/Library/Application Support/Sublime Text 3/Installed Packages/Browser Refresh.sublime-package
```

**Comment by aheissenberger** [comment]
after installing directly from git I reloaded as suggest #69 and it worked again
